[build]
  publish = ".next"
  command = "npm run build"


[[redirects]]
  from = "/revalidation/*"
  to = "/resources/blog/?redirected=:splat"
  status = 302
  headers = {X-From = "Netlify-Test"}

[[redirects]]
  from = "/revalidation2/*"
  to = "/resources/blog/?redirected=:splat"
  status = 302

[[redirects]]
  from = "/resources/*"
  to = "/resources/?redirected=:splat"
  status = 302

